from enum import Enum


class NodeType(str, Enum):
    PROGRAM = "PROGRAM"
    BLOCK = "BLOCK"
    
    EXPRESSION = "EXPRESSION"
    SIMPLE_EXPRESSION = "SIMPLE_EXPRESSION"
    TERM = "TERM"
    FACTOR = "FACTOR"

    VAR_DECL = "VAR_DECL"
    ASSIGN_STMT = "ASSIGN"
    PRINT_STMT = "PRINT"
    IF_STMT = "IF"
    WHILE_STMT = "WHILE"
    RETURN_STMT = "RETURN"
    FUNCTION_DECL = "FUNCTION_DECL"

    PARAM = "PARAM"
    PARAM_LIST = "PARAM_LIST"
    ARG_LIST = "ARG_LIST"
    FUNCTION_CALL = "FUNCTION_CALL"

    BINARY_OP = "BINARY_OP"
    UNARY_OP = "UNARY_OP"

    IDENTIFIER = "IDENTIFIER"
    LITERAL = "LITERAL"

    TYPE_STMT = "TYPE"
